# Ejercicios Tema 1 (Estadistica)

### Ejercicio 1 Se considera la matriz

$\left(A=\begin{array}{lll}
0 & -1 & 1 \\
0 & 1 & -1 \\ 0 & 0 & 1
\end{array}
\right)
$

Hallar una fórmula para $A^n$, siendo n un entero positivo

In [3]:
# Importamos la libreria de numpy
import numpy as np

In [84]:
# Creamos la matriz mediante una lista que numpy declara como array.
A=np.array([[0,-1,1],[0,1,-1],[0,0,1]])
A

array([[ 0, -1,  1],
       [ 0,  1, -1],
       [ 0,  0,  1]])

In [29]:
# Vamos a hallar una formula para $A^n$, siendo n un número positivo

# Vamos a probar con n=2
A_dos= A*A
A_tres=A_dos*A
print ("La matriz para n=2 es: ",A_dos )


print ("La matriz para n=3 es:", A_tres)

La matriz para n=2 es:  [[0 1 1]
 [0 1 1]
 [0 0 1]]
La matriz para n=3 es: [[ 0 -1  1]
 [ 0  1 -1]
 [ 0  0  1]]


## Solución:

Si n es un número par la matriz va a ser:
$\left(A=\begin{array}{lll}
0 & 1 & 1 \\
0 & 1 & 1 \\ 0 & 0 & 1
\end{array}
\right)
$

Por el contrario si es impar:
$\left(A=\begin{array}{lll}
0 & -1 & 1 \\
0 & 1 & -1 \\ 0 & 0 & 1
\end{array}
\right)
$

Todo es se debe a los signos negativos que tiene la matriz.

## Ejercicio 2 Dada la matriz: 


## Ejercicio 3. Transforme la matriz A en una matriz escalonada reducida por filas: 
$\left(A=\begin{array}{lll}
2 & 3 & 1 & 4 \\
3 & 1 & 2 & 0\\ 1 & 2 & 4 & 1
\end{array}
\right)
$

In [85]:
# Creamos la matriz:
B=np.array([[2,3,1,4],[3,1,2,0],[1,2,4,1]])
B

array([[2, 3, 1, 4],
       [3, 1, 2, 0],
       [1, 2, 4, 1]])

In [108]:
escalonada_F_1 = B[0]-1
escalonada_F_2 = B[2]-escalonada_F_1
escalonada_F_2

array([ 0,  0,  4, -2])

In [117]:
B_modificada=np.array([[np.array(escalonada_F_1)],[np.array(escalonada_F_2)],B[1]])
type(B_modificada)

C:\Users\Alvaro Díaz\AppData\Local\Temp\ipykernel_21268\3992919410.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  B_modificada=np.array([[np.array(escalonada_F_1)],[np.array(escalonada_F_2)],B[1]])


numpy.ndarray